create sequence tb_itempedido_id_itempedido_seq start with 1 increment by 1;
create sequence tb_pedidos_id_pedido_seq start with 1 increment by 1;
create sequence tb_produtos_id_produto_seq start with 1 increment by 1;
create sequence usuario_seq start with 1 increment by 50;
create table tb_itempedido (qtde_itempedido integer, fk_pedido bigint, fk_produto bigint, id_itempedido bigint not null, primary key (id_itempedido));
create table tb_pedidos (id_pedido bigint not null, bairro_pedido varchar(255), cidade_pedido varchar(255), logradouro_pedido varchar(255), nome_cliente_pedido varchar(255), numero_predial_pedido varchar(255), opcao_pagamento varchar(255), referencia_pedido varchar(255), tel_cliente_pedido varchar(255), url_pedido varchar(255), primary key (id_pedido));
create table tb_produtos (preco_produto float(53), id_produto bigint not null, imagem_produto varchar(255), nome_produto varchar(255), primary key (id_produto));
create table tb_usuarios (id_usuario bigint not null, salt_usuario varchar(64), login_usuario varchar(255), nome_usuario varchar(255), senha_usuario varchar(255), primary key (id_usuario));
alter table if exists tb_itempedido add constraint FKs1kh5ph2ogmknptihtg91wnia foreign key (fk_pedido) references tb_pedidos;
alter table if exists tb_itempedido add constraint FKdtaqrcrp8ptr111ocj1hny04u foreign key (fk_produto) references tb_produtos;
create sequence tb_itempedido_id_itempedido_seq start with 1 increment by 1;
create sequence tb_pedidos_id_pedido_seq start with 1 increment by 1;
create sequence tb_produtos_id_produto_seq start with 1 increment by 1;
create sequence usuario_seq start with 1 increment by 50;
create table tb_itempedido (qtde_itempedido integer, fk_pedido bigint, fk_produto bigint, id_itempedido bigint not null, primary key (id_itempedido));
create table tb_pedidos (id_pedido bigint not null, bairro_pedido varchar(255), cidade_pedido varchar(255), logradouro_pedido varchar(255), nome_cliente_pedido varchar(255), numero_predial_pedido varchar(255), opcao_pagamento varchar(255), referencia_pedido varchar(255), tel_cliente_pedido varchar(255), url_pedido varchar(255), primary key (id_pedido));
create table tb_produtos (preco_produto float(53), id_produto bigint not null, imagem_produto varchar(255), nome_produto varchar(255), primary key (id_produto));
create table tb_usuarios (id_usuario bigint not null, salt_usuario varchar(64), login_usuario varchar(255), nome_usuario varchar(255), senha_usuario varchar(255), primary key (id_usuario));
alter table if exists tb_itempedido add constraint FKs1kh5ph2ogmknptihtg91wnia foreign key (fk_pedido) references tb_pedidos;
alter table if exists tb_itempedido add constraint FKdtaqrcrp8ptr111ocj1hny04u foreign key (fk_produto) references tb_produtos;
create sequence tb_itempedido_id_itempedido_seq start with 1 increment by 1;
create sequence tb_pedidos_id_pedido_seq start with 1 increment by 1;
create sequence tb_produtos_id_produto_seq start with 1 increment by 1;
create sequence usuario_seq start with 1 increment by 50;
create table tb_itempedido (qtde_itempedido integer, fk_pedido bigint, fk_produto bigint, id_itempedido bigint not null, primary key (id_itempedido));
create table tb_pedidos (id_pedido bigint not null, bairro_pedido varchar(255), cidade_pedido varchar(255), logradouro_pedido varchar(255), nome_cliente_pedido varchar(255), numero_predial_pedido varchar(255), opcao_pagamento varchar(255), referencia_pedido varchar(255), tel_cliente_pedido varchar(255), url_pedido varchar(255), primary key (id_pedido));
create table tb_produtos (preco_produto float(53), id_produto bigint not null, imagem_produto varchar(255), nome_produto varchar(255), primary key (id_produto));
create table tb_usuarios (id_usuario bigint not null, salt_usuario varchar(64), login_usuario varchar(255), nome_usuario varchar(255), senha_usuario varchar(255), primary key (id_usuario));
alter table if exists tb_itempedido add constraint FKs1kh5ph2ogmknptihtg91wnia foreign key (fk_pedido) references tb_pedidos;
alter table if exists tb_itempedido add constraint FKdtaqrcrp8ptr111ocj1hny04u foreign key (fk_produto) references tb_produtos;
create sequence tb_itempedido_id_itempedido_seq start with 1 increment by 1;
create sequence tb_pedidos_id_pedido_seq start with 1 increment by 1;
create sequence tb_produtos_id_produto_seq start with 1 increment by 1;
create sequence usuario_seq start with 1 increment by 50;
create table tb_itempedido (qtde_itempedido integer, fk_pedido bigint, fk_produto bigint, id_itempedido bigint not null, primary key (id_itempedido));
create table tb_pedidos (id_pedido bigint not null, bairro_pedido varchar(255), cidade_pedido varchar(255), logradouro_pedido varchar(255), nome_cliente_pedido varchar(255), numero_predial_pedido varchar(255), opcao_pagamento varchar(255), referencia_pedido varchar(255), tel_cliente_pedido varchar(255), url_pedido varchar(255), primary key (id_pedido));
create table tb_produtos (preco_produto float(53), id_produto bigint not null, imagem_produto varchar(255), nome_produto varchar(255), primary key (id_produto));
create table tb_usuarios (id_usuario bigint not null, salt_usuario varchar(64), login_usuario varchar(255), nome_usuario varchar(255), senha_usuario varchar(255), primary key (id_usuario));
alter table if exists tb_itempedido add constraint FKs1kh5ph2ogmknptihtg91wnia foreign key (fk_pedido) references tb_pedidos;
alter table if exists tb_itempedido add constraint FKdtaqrcrp8ptr111ocj1hny04u foreign key (fk_produto) references tb_produtos;
